packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@swc/core': true
  cpu-features: set this to true or false
  protobufjs: set this to true or false
  sharp: true
  ssh2: set this to true or false
  unrs-resolver: true
